# SPDX-License-Identifier: MIT
# Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.

workspace(name = "com_atomgit_openeuler_umdk_urpc")

new_local_repository(
    name = "urma",
    build_file = "//third_party/urma:BUILD.bazel",
    path = "/usr",
)
