# SPDX-License-Identifier: MIT
# Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.

$template ums_agent_file_path,"/var/log/umdk/ums/ums_agent/ums_agent.log"
$template umsAgentLogMsg,"%TIMESTAMP:::date-rfc3339%|%syslogseverity-text%|%programname%[%PROCID%]|%msg%\n"

if $programname == 'ums_agent' then ?ums_agent_file_path;umsAgentLogMsg
