/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2026. All rights reserved.
 */

// Code generated by "stringer -type StatType"; DO NOT EDIT.

package stats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScheduleSuccess-0]
	_ = x[ScheduleFailure-1]
	_ = x[TokenizerEncodeError-2]
	_ = x[LightGbmVectorizeError-3]
	_ = x[LightGbmPredictError-4]
	_ = x[CapacityLbInsufficientFreeBlocks-5]
	_ = x[CapacityLbLatencyOverLimit-6]
	_ = x[TokenLbLatencyOverLimit-7]
	_ = x[LbNoInstances-8]
	_ = x[StatAgentRegistered-9]
	_ = x[StatAgentActive-10]
	_ = x[StatAgentSuspected-11]
	_ = x[StatAgentRecovered-12]
	_ = x[StatAgentGone-13]
	_ = x[StatAgentUnregistered-14]
	_ = x[StatSessionsActive-15]
	_ = x[StatSessionsSuspended-16]
	_ = x[StatSessionsRecovering-17]
	_ = x[StatSessionsTerminated-18]
	_ = x[StatSessionsEvicted-19]
	_ = x[StatHintsIssuedOffload-20]
	_ = x[StatHintsIssuedPrefetch-21]
	_ = x[StatHintsIssuedEvict-22]
	_ = x[StatHintsAcked-23]
	_ = x[StatHintsRejected-24]
	_ = x[StatHintsFailed-25]
	_ = x[StatHintsRetried-26]
	_ = x[StatHintsPending-27]
	_ = x[StatBlocksTracked-28]
	_ = x[StatBlocksAttributed-29]
	_ = x[StatBlockMatchMiss-30]
	_ = x[TypeCount-31]
}

const _StatType_name = "ScheduleSuccessScheduleFailureTokenizerEncodeErrorLightGbmVectorizeErrorLightGbmPredictErrorCapacityLbInsufficientFreeBlocksCapacityLbLatencyOverLimitTokenLbLatencyOverLimitLbNoInstancesStatAgentRegisteredStatAgentActiveStatAgentSuspectedStatAgentRecoveredStatAgentGoneStatAgentUnregisteredStatSessionsActiveStatSessionsSuspendedStatSessionsRecoveringStatSessionsTerminatedStatSessionsEvictedStatHintsIssuedOffloadStatHintsIssuedPrefetchStatHintsIssuedEvictStatHintsAckedStatHintsRejectedStatHintsFailedStatHintsRetriedStatHintsPendingStatBlocksTrackedStatBlocksAttributedStatBlockMatchMissTypeCount"

var _StatType_index = [...]uint16{0, 15, 30, 50, 72, 92, 124, 150, 173, 186, 205, 220, 238, 256, 269, 290, 308, 329, 351, 373, 392, 414, 437, 457, 471, 488, 503, 519, 535, 552, 572, 590, 599}

func (i StatType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StatType_index)-1 {
		return "StatType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatType_name[_StatType_index[idx]:_StatType_index[idx+1]]
}
