/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 * Description: Code generated by "stringer -type StatType"; DO NOT EDIT.
 * Create: 2025-08-01
 */

package stats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScheduleSuccess-0]
	_ = x[ScheduleFailure-1]
	_ = x[TokenizerEncodeError-2]
	_ = x[LightGbmVectorizeError-3]
	_ = x[LightGbmPredictError-4]
	_ = x[CapacityLbInsufficientFreeBlocks-5]
	_ = x[CapacityLbLatencyOverLimit-6]
	_ = x[TokenLbLatencyOverLimit-7]
	_ = x[LbNoInstances-8]
	_ = x[TypeCount-9]
}

const _StatType_name = "ScheduleSuccessScheduleFailureTokenizerEncodeErrorLightGbmVectorizeErrorLightGbmPredictErrorCapacityLbInsufficientFreeBlocksCapacityLbLatencyOverLimitTokenLbLatencyOverLimitLbNoInstancesTypeCount"

var _StatType_index = [...]uint8{0, 15, 30, 50, 72, 92, 124, 150, 173, 186, 195}

func (i StatType) String() string {
	if i < 0 || i >= StatType(len(_StatType_index)-1) {
		return "StatType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatType_name[_StatType_index[i]:_StatType_index[i+1]]
}
