/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 * Description: FusedDeepMoe operator kernel function implementation file
 * Create: 2025-07-19
 * Note:
 * History: 2025-07-19 create FusedDeepMoe operator kernel function implementation file
 */
#include "fused_deep_moe.h"
#include <kernel_operator.h>
#include "lib/matmul_intf.h"

#define CALL_FUSED_DEEP_MOE \
        FusedDeepMoe<DTYPE_X, DTYPE_GMM1_WEIGHT_SCALE, DTYPE_GMM2_WEIGHT_SCALE, int32_t, false, TILING_KEY_VAR> op; \
        op.Init(x, expert_ids, gmm1_weight, gmm1_weight_scale, gmm2_weight, gmm2_weight_scale, \
                expert_scales, share_gmm1_weight, share_gmm1_weight_scale, \
                share_gmm2_weight, share_gmm2_weight_scale, expert_smooth_scales, share_smooth_scales, x_active_mask, \
                gmm1_bias, gmm2_bias, share_gmm1_bias, share_gmm2_bias, \
                output, share_output, expertTokenNums, \
                workspace, nullptr, &tiling_data); \
        op.Process()

#define CALL_FUSED_DEEP_MOE_IF_TILINGKEY(tilingKey) \
    if constexpr (TILING_KEY_IS(tilingKey)) { \
        CALL_FUSED_DEEP_MOE; \
    }

#define CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(tilingKey) \
    else if constexpr (TILING_KEY_IS(tilingKey)) { \
        CALL_FUSED_DEEP_MOE; \
    }

extern "C" __global__ __aicore__ void fused_deep_moe(
    // input
    GM_ADDR x, GM_ADDR expert_ids, GM_ADDR gmm1_weight, GM_ADDR gmm1_weight_scale,
    GM_ADDR gmm2_weight, GM_ADDR gmm2_weight_scale, GM_ADDR expert_scales,
    GM_ADDR share_gmm1_weight, GM_ADDR share_gmm1_weight_scale,
    GM_ADDR share_gmm2_weight, GM_ADDR share_gmm2_weight_scale,
    GM_ADDR expert_smooth_scales, GM_ADDR share_smooth_scales, GM_ADDR x_active_mask,
    // W4A8: bias/compensation matrix
    GM_ADDR gmm1_bias, GM_ADDR gmm2_bias,
    GM_ADDR share_gmm1_bias, GM_ADDR share_gmm2_bias,
    // output
    GM_ADDR output, GM_ADDR share_output, GM_ADDR expertTokenNums,
    // system
    GM_ADDR workspace, GM_ADDR tiling)
{
    icache_preload(8);
    REGISTER_TILING_DEFAULT(FusedDeepMoeTilingData);
    KERNEL_TASK_TYPE_DEFAULT(KERNEL_TYPE_MIX_AIC_1_2);  // 1C2V
    GET_TILING_DATA(tiling_data, tiling);
    CALL_FUSED_DEEP_MOE_IF_TILINGKEY(0)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(1)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(2)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(3)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(4)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(5)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(6)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(7)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(8)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(9)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(10)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(11)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(12)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(13)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(14)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(15)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(16)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(17)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(18)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(19)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(20)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(21)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(22)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(23)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(24)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(25)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(26)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(27)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(28)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(29)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(30)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(31)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(32)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(33)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(34)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(35)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(36)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(37)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(38)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(39)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(40)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(41)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(42)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(43)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(44)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(45)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(46)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(47)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(48)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(49)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(50)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(51)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(52)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(53)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(54)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(55)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(56)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(57)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(58)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(59)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(60)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(61)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(62)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(63)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(64)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(65)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(66)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(67)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(68)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(69)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(70)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(71)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(72)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(73)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(74)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(75)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(76)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(77)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(78)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(79)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(80)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(81)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(82)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(83)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(84)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(85)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(86)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(87)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(88)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(89)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(90)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(91)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(92)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(93)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(94)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(95)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(96)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(97)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(98)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(99)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(100)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(101)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(102)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(103)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(104)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(105)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(106)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(107)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(108)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(109)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(110)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(111)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(112)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(113)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(114)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(115)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(116)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(117)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(118)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(119)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(120)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(121)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(122)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(123)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(124)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(125)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(126)
    CALL_FUSED_DEEP_MOE_ELIF_TILINGKEY(127)
}
