#!/bin/sh

set -e

case "$1" in
    configure)
        if [ -x /bin/systemctl ]; then
            /bin/systemctl daemon-reload >/dev/null 2>&1 || true
        fi
        if [ -x /bin/systemctl ] && [ -x /usr/sbin/rsyslogd ]; then
            /bin/systemctl restart rsyslog >/dev/null 2>&1 || true
        fi
        chmod +x /lib/libtpsa*.so*
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
