# SPDX-License-Identifier: MIT
# Copyright (c) Huawei Technologies Co., Ltd. 2021-2025. All rights reserved.

#The "UrmaAdminDynamicFile" name is globally unique in the runtime environment,
#otherwise the conflict will not generate a log file.
$template UrmaAdminDynamicFile,"/var/log/umdk/urma/%programname%.log"
$template urmaAdminLogMsg,"%TIMESTAMP:::date-rfc3339%|%syslogseverity-text%|%programname%[%PROCID%]|%msg%\n"

if $msg startswith 'URMA|urma_admin' then ?UrmaAdminDynamicFile;urmaAdminLogMsg