/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
 * Description: rack topology loader
 * Create: 2026-09-09
 * Note: 2026-09-17 rewritten to load the locally generated topo JSON
 *       (test/snc/resources/topo_data_full_rack.json, written by
 *       FullRackTopologyGenerator) into an in-memory SuperNode, replacing
 *       the removed FullRackTopologyGenerator.buildRawTopology() path.
 *       Same day: when the default topo file is missing (e.g. on a clean
 *       CI checkout where the multi-hundred-MB artifact is not part of the
 *       repository), it is auto-generated with FullRackTopologyGenerator.
 */
package com.huawei.umdk.snc;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.huawei.umdk.snc.entity.DeviceEntity;
import com.huawei.umdk.snc.entity.ForwardingChip;
import com.huawei.umdk.snc.entity.NpuDevice;
import com.huawei.umdk.snc.entity.NpuForwardingChip;
import com.huawei.umdk.snc.entity.NpuPortEntity;
import com.huawei.umdk.snc.entity.OutPortInfo;
import com.huawei.umdk.snc.entity.RoutePrefix;
import com.huawei.umdk.snc.entity.RoutingEntry;
import com.huawei.umdk.snc.entity.RoutingTable;
import com.huawei.umdk.snc.entity.SuperNode;
import com.huawei.umdk.snc.entity.SwDevice;
import com.huawei.umdk.snc.entity.SwForwardingChip;
import com.huawei.umdk.snc.entity.SwPortEntity;
import com.huawei.umdk.snc.entity.SwitchLevel;

/**
 * Loads the full rack topology into an in-memory {@link SuperNode} from the
 * locally generated topo JSON file (default
 * {@code test/snc/resources/topo_data_full_rack.json}, written by
 * {@link FullRackTopologyGenerator}).
 *
 * <p>The JSON format (per device): {@code forwardingChip} is an array of chip
 * objects, each containing {@code chipIndex}, {@code ports}, {@code logicPorts}
 * and its own {@code routingTables}. Switch devices may carry multiple chips
 * (each L2SW has two). A device-level {@code routingTables} array (legacy
 * fixture style) is accepted as a fallback.
 *
 * <p>The file is streamed device-by-device so that the multi-hundred-MB full
 * rack JSON never needs to be materialized as a single JSON tree.
 *
 * <p>When the default file is not found anywhere (e.g. on a clean CI
 * checkout, since the generated JSON is not committed to the repository),
 * it is automatically generated by invoking {@link FullRackTopologyGenerator}
 * — the single source of truth for the topology — and then loaded. The
 * generator anchors its output at {@code <classRoot>/../resources}, which
 * is the last resolution step before auto-generation.
 */
public final class RackTopologyLoader {

    /** Default topo file name produced by {@link FullRackTopologyGenerator}. */
    public static final String DEFAULT_TOPO_FILE = "topo_data_full_rack.json";

    /** System property overriding the topo file name/path used by {@link #loadRawTopology()}. */
    public static final String TOPO_FILE_PROPERTY = "snc.topo.file";

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private RackTopologyLoader() {
    }

    /**
     * Builds the full rack topology in memory from the locally generated topo
     * JSON (default {@value #DEFAULT_TOPO_FILE}, overridable via the
     * {@value #TOPO_FILE_PROPERTY} system property).
     *
     * <p>The file is resolved as (first match wins):
     * <ol>
     *   <li>an existing file path (absolute or CWD-relative);</li>
     *   <li>{@code <cwd>/test/snc/resources/<name>} (run from the repo root);</li>
     *   <li>{@code <cwd>/resources/<name>} (run from test/snc);</li>
     *   <li>classpath resource (Maven copies test resources to
     *       target/test-classes);</li>
     *   <li>{@code <classRoot>/../resources/<name>} (mirrors the generator's
     *       output anchoring, e.g. {@code java -cp test/snc/java});</li>
     *   <li>auto-generation: the default file is generated with
     *       {@link FullRackTopologyGenerator} and loaded (clean CI checkout
     *       fallback).</li>
     * </ol>
     *
     * @return a SuperNode containing all devices from the JSON
     */
    public static SuperNode loadRawTopology() {
        String override = System.getProperty(TOPO_FILE_PROPERTY);
        return loadTopologyFile(override != null ? override : DEFAULT_TOPO_FILE);
    }

    /**
     * Same as {@link #loadRawTopology()} but with an explicit topo file: either
     * a path or a bare file name resolved against the standard resource
     * directories (e.g. {@code topo_data_full_rack_800g.json}).
     *
     * @param fileNameOrPath topo JSON path or resource file name
     * @return a SuperNode containing all devices from the JSON
     */
    public static SuperNode loadRawTopology(String fileNameOrPath) {
        return loadTopologyFile(fileNameOrPath);
    }

    // ------------------------------------------------------------------
    //  File resolution
    // ------------------------------------------------------------------

    private static SuperNode loadTopologyFile(String fileNameOrPath) {
        try {
            // 1-3. Explicit path and CWD-anchored resource dirs.
            Path file = resolveTopoFile(fileNameOrPath);
            if (file != null) {
                return parseFile(file, file.toString());
            }
            // 4. Classpath resource (Maven copies test resources to
            //    target/test-classes; reflects a locally customized file).
            String resource = "/" + fileNameOrPath.replace('\\', '/');
            try (InputStream is = RackTopologyLoader.class.getResourceAsStream(resource)) {
                if (is != null) {
                    try (JsonParser p = MAPPER.createParser(is)) {
                        return parseTopology(p, "classpath:" + resource);
                    }
                }
            }
            // 5. Class-anchored <classRoot>/../resources (the generator's
            //    output anchoring, e.g. for java -cp test/snc/java runs).
            Path anchored = resolveClassAnchoredFile(fileNameOrPath);
            if (anchored != null) {
                return parseFile(anchored, anchored.toString());
            }
            // 6. Auto-generate the default topo file when everything above
            //    missed (clean CI checkout) and load it.
            if (DEFAULT_TOPO_FILE.equals(fileNameOrPath)) {
                Path generated = generateDefaultTopoFile();
                if (generated != null) {
                    return parseFile(generated, generated + " (auto-generated)");
                }
            }
            throw new IllegalStateException(notFoundMessage(fileNameOrPath));
        } catch (IOException e) {
            throw new IllegalStateException(
                "Failed to read rack topology from " + fileNameOrPath, e);
        }
    }

    private static SuperNode parseFile(Path file, String source) throws IOException {
        try (JsonParser p = MAPPER.createParser(file.toFile())) {
            return parseTopology(p, source);
        }
    }

    /**
     * Generates the default topo JSON with {@link FullRackTopologyGenerator}
     * when it is absent, and returns the generated file. The generator anchors
     * its output at {@code <classRoot>/../resources}, so the re-resolve after
     * generation finds it there (with a CWD-relative retry for the generator's
     * own fallback location).
     */
    private static Path generateDefaultTopoFile() {
        System.out.println("RackTopologyLoader: " + DEFAULT_TOPO_FILE
            + " not found, generating it with FullRackTopologyGenerator...");
        try {
            FullRackTopologyGenerator.main(new String[0]);
        } catch (IOException e) {
            throw new IllegalStateException(
                "Failed to generate " + DEFAULT_TOPO_FILE
                    + " with FullRackTopologyGenerator", e);
        }
        Path generated = resolveClassAnchoredFile(DEFAULT_TOPO_FILE);
        if (generated == null) {
            generated = resolveTopoFile(DEFAULT_TOPO_FILE);
        }
        return generated;
    }

    private static Path resolveTopoFile(String fileNameOrPath) {
        // 1. Existing file path (absolute or CWD-relative).
        Path direct = Paths.get(fileNameOrPath);
        if (Files.isRegularFile(direct)) {
            return direct;
        }
        // 2./3. CWD-anchored resource dirs (repo root / test/snc).
        Path cwd = Paths.get("").toAbsolutePath();
        for (String dir : new String[] {"test/snc/resources", "resources"}) {
            Path candidate = cwd.resolve(dir).resolve(fileNameOrPath);
            if (Files.isRegularFile(candidate)) {
                return candidate;
            }
        }
        return null;
    }

    private static Path resolveClassAnchoredFile(String fileNameOrPath) {
        // Mirrors FullRackTopologyGenerator's OUTPUT_FILE anchoring
        // (<classRoot>/../resources/<name>).
        try {
            Path classRoot = Paths.get(RackTopologyLoader.class.getProtectionDomain()
                .getCodeSource().getLocation().toURI());
            Path candidate = classRoot.resolve("..").resolve("resources")
                .normalize().resolve(fileNameOrPath);
            if (Files.isRegularFile(candidate)) {
                return candidate;
            }
        } catch (Exception ignored) {
            // Class location unavailable.
        }
        return null;
    }

    private static String notFoundMessage(String fileNameOrPath) {
        String genNote = DEFAULT_TOPO_FILE.equals(fileNameOrPath)
            ? " Auto-generation with FullRackTopologyGenerator was attempted"
                + " but no file appeared."
            : "";
        return "Rack topology file not found: " + fileNameOrPath
            + " (checked the explicit path, <cwd>/test/snc/resources, <cwd>/resources,"
            + " the classpath and <classRoot>/../resources)." + genNote
            + " Point -D" + TOPO_FILE_PROPERTY + "=<path> at an existing file.";
    }

    // ------------------------------------------------------------------
    //  Streaming JSON -> SuperNode
    // ------------------------------------------------------------------

    private static SuperNode parseTopology(JsonParser p, String source) throws IOException {
        String name = null;
        String version = null;
        Map<String, NpuDevice> npuDevices = new LinkedHashMap<>();
        Map<String, SwDevice> swDevices = new LinkedHashMap<>();

        if (p.nextToken() != JsonToken.START_OBJECT) {
            throw new IOException("Malformed topology JSON, expected root object: " + source);
        }
        while (p.nextToken() == JsonToken.FIELD_NAME) {
            String field = p.currentName();
            p.nextToken();
            if ("name".equals(field)) {
                name = p.getText();
            } else if ("version".equals(field)) {
                version = p.getText();
            } else if ("devices".equals(field)) {
                if (p.currentToken() != JsonToken.START_OBJECT) {
                    throw new IOException("Malformed topology JSON, devices must be an object: "
                        + source);
                }
                while (p.nextToken() == JsonToken.FIELD_NAME) {
                    p.nextToken();
                    JsonNode deviceNode = MAPPER.readTree(p);
                    DeviceEntity device = parseDevice(deviceNode);
                    if (device instanceof NpuDevice) {
                        npuDevices.put(device.getDeviceName(), (NpuDevice) device);
                    } else {
                        swDevices.put(device.getDeviceName(), (SwDevice) device);
                    }
                }
            } else {
                p.skipChildren();
            }
        }

        if (npuDevices.isEmpty() && swDevices.isEmpty()) {
            throw new IOException("No devices found in topology: " + source);
        }
        System.out.println("RackTopologyLoader: loaded " + (npuDevices.size() + swDevices.size())
            + " devices (" + npuDevices.size() + " NPU, " + swDevices.size() + " SW)"
            + " from " + source);
        return new SuperNode(name, version, npuDevices, swDevices);
    }

    // ------------------------------------------------------------------
    //  Device parsing
    // ------------------------------------------------------------------

    private static DeviceEntity parseDevice(JsonNode node) {
        String deviceName = node.get("deviceName").asText();
        String type = node.get("deviceType").asText();
        String rack = node.has("rack") ? node.get("rack").asText() : null;

        if ("NPU".equals(type)) {
            return parseNpuDevice(node, deviceName, rack);
        }
        if ("SW".equals(type)) {
            return parseSwDevice(node, deviceName, rack);
        }
        throw new IllegalStateException("Unknown device type: " + type + " for " + deviceName);
    }

    private static NpuDevice parseNpuDevice(JsonNode node, String deviceName, String rack) {
        NpuDevice npu = new NpuDevice();
        npu.setDeviceName(deviceName);
        npu.setRack(rack);
        npu.setOsName(node.has("osName") ? node.get("osName").asText() : null);
        npu.setOsIp(node.has("osIp") ? node.get("osIp").asText() : null);
        npu.setBoardId(node.has("boardId") ? node.get("boardId").asInt() : null);
        npu.setModuleId(node.has("moduleId") ? node.get("moduleId").asInt() : null);
        npu.setBoardIndex(node.has("boardIndex") ? node.get("boardIndex").asInt() : null);

        Map<Integer, NpuForwardingChip> chips = new LinkedHashMap<>();
        for (JsonNode fcNode : node.get("forwardingChip")) {
            NpuForwardingChip chip = new NpuForwardingChip();
            chip.setChipIndex(fcNode.get("chipIndex").asInt());
            chip.setPorts(parseNpuPorts(fcNode.get("ports"), chip.getChipIndex()));
            attachRoutingTable(node, fcNode, deviceName, chip);
            chips.put(chip.getChipIndex(), chip);
        }
        npu.setForwardingChips(chips);
        return npu;
    }

    private static SwDevice parseSwDevice(JsonNode node, String deviceName, String rack) {
        SwDevice sw = new SwDevice();
        sw.setDeviceName(deviceName);
        sw.setRack(rack);
        String level = node.has("level") ? node.get("level").asText() : "L1";
        sw.setSwitchLevel("L2".equals(level) ? SwitchLevel.L2 : SwitchLevel.L1);
        sw.setIndex(node.has("index") ? node.get("index").asInt() : null);

        Map<Integer, SwForwardingChip> chips = new LinkedHashMap<>();
        for (JsonNode fcNode : node.get("forwardingChip")) {
            SwForwardingChip chip = new SwForwardingChip();
            chip.setChipIndex(fcNode.get("chipIndex").asInt());
            chip.setPorts(parseSwPorts(fcNode.get("ports"), chip.getChipIndex()));
            attachRoutingTable(node, fcNode, deviceName, chip);
            chips.put(chip.getChipIndex(), chip);
        }
        sw.setForwardingChips(chips);
        return sw;
    }

    // ------------------------------------------------------------------
    //  Port parsing
    // ------------------------------------------------------------------

    private static Map<String, NpuPortEntity> parseNpuPorts(JsonNode portsArray, int chipIndex) {
        Map<String, NpuPortEntity> ports = new LinkedHashMap<>();
        for (JsonNode portNode : portsArray) {
            NpuPortEntity port = new NpuPortEntity(
                portNode.has("eid") ? portNode.get("eid").asText() : null,
                portNode.has("upi") ? portNode.get("upi").asText() : null);
            port.setPortName(portNode.get("portName").asText());
            port.setId(portNode.get("id").asInt());
            port.setChipIndex(chipIndex);
            port.setRemoteDevice(portNode.get("remoteDevice").asText());
            port.setRemotePort(portNode.get("remotePort").asText());
            port.setCna(portNode.has("cna") ? portNode.get("cna").asText() : null);
            ports.put(port.getPortName(), port);
        }
        return ports;
    }

    private static Map<String, SwPortEntity> parseSwPorts(JsonNode portsArray, int chipIndex) {
        Map<String, SwPortEntity> ports = new LinkedHashMap<>();
        for (JsonNode portNode : portsArray) {
            SwPortEntity port = new SwPortEntity();
            port.setPortName(portNode.get("portName").asText());
            port.setId(portNode.get("id").asInt());
            port.setChipIndex(chipIndex);
            port.setRemoteDevice(portNode.get("remoteDevice").asText());
            port.setRemotePort(portNode.get("remotePort").asText());
            ports.put(port.getPortName(), port);
        }
        return ports;
    }

    // ------------------------------------------------------------------
    //  Routing table parsing
    // ------------------------------------------------------------------

    /**
     * Attaches the chip's routing table. routingTables live inside the chip
     * object in the full-rack generator format; a device-level array (legacy
     * fixture style) is used as fallback.
     */
    private static void attachRoutingTable(JsonNode deviceNode, JsonNode chipNode,
                                           String deviceName, ForwardingChip chip) {
        JsonNode routingTables = chipNode.has("routingTables")
            ? chipNode.get("routingTables")
            : deviceNode.get("routingTables");
        if (routingTables == null || !routingTables.isArray()) {
            return;
        }

        RoutingTable rt = new RoutingTable();
        rt.setDeviceName(deviceName);
        rt.setChipIndex(chip.getChipIndex());
        Map<RoutePrefix, RoutingEntry> routes = new LinkedHashMap<>();

        for (JsonNode rtNode : routingTables) {
            JsonNode prefixNode = rtNode.get("prefix");
            RoutePrefix prefix = new RoutePrefix(
                prefixNode.get("dstAddress").asText(),
                prefixNode.get("maskLength").asInt());

            Map<String, OutPortInfo> outPortInfos = new LinkedHashMap<>();
            for (JsonNode opiNode : rtNode.get("outPortInfos")) {
                String outInterface = opiNode.get("outInterface").asText();
                OutPortInfo opi = new OutPortInfo(
                    outInterface,
                    opiNode.has("nextHop") ? opiNode.get("nextHop").asText() : "",
                    opiNode.has("preference") ? opiNode.get("preference").asInt() : 60,
                    opiNode.has("tag") ? opiNode.get("tag").asInt() : 0,
                    opiNode.has("protocol") ? opiNode.get("protocol").asText() : "static",
                    0);
                outPortInfos.put(outInterface, opi);
            }

            routes.put(prefix, new RoutingEntry(prefix, outPortInfos, true));
        }

        rt.setRoutes(routes);
        List<Integer> masks = routes.keySet().stream()
            .map(RoutePrefix::getMaskLength)
            .sorted(Comparator.reverseOrder())
            .collect(Collectors.toList());
        rt.setMaskLengths(masks);
        chip.setRoutingTable(rt);
    }
}
